spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true


management.server.port: 8081

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://otel-lgtm:4317

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE